stages:
  - mirror
  - test

GH Mirror:
  stage: mirror
  image: haffmans/git-mirror:latest
  script:
    - git-mirror "${CI_PROJECT_DIR}" git@github.com:${GITHUB_REPOSITORY}

Tests:
  stage: test
  image: "rust:latest"

  test:cargo:
    script:
    - rustc --version && cargo --version
    - cargo test --all --verbose -- --test-threads=1

